default:
  image: tjpa-registry-quay-quay-enterprise.apps.ocp-hub.i.tj.pa.gov.br/devops/runner-tools:latest
  tags:
    - rke

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'  # Trigger manual
    - when: never                         # Bloqueia outros

stages:
  - prepare
  - deploy

variables:
  # 1. Target Environment
  ENV_: 
    description: "Environment where the project will be deployed"
    value: "prd"
    options:
      - "hml"
      - "prd"
      - "dev"

  # 2. Enable Custom Application (CA) source
  ENABLE_CA_SOURCE:
    description: "Enable values from gitlab-ca as source"
    value: "false"
    options:
      - "false"
      - "true"

  # 3. Dev Application Repository Revision
  DEV_APP_REPO_REVISION:
    description: "Branch, tag or commit SHA for the developer CA source repository:"
    value: "main"
    options:
      - "main"
      - "hml"
      - "dev"
      - "develop"
      - "homolog"

  # 4. Dynamic Values File Path
  DEV_VALUES_PATH:
    description: "Location and format of the values file in the repository (change env to match the desired environment)"
    value: "values-env.yaml"

get_chart_version:
  stage: prepare
  script:
    - export CHART_VERSION="$(grep -E '^[[:space:]]*version:[[:space:]]*' chart/Chart.yaml | head -n1 | sed -E 's/^[[:space:]]*version:[[:space:]]*//')"
    - echo "Detected chart version $CHART_VERSION"
    - export DEV_APP_REPO_URL="$(grep -E '^[[:space:]]*tjpa.jus.br/dev-source-repo:[[:space:]]*' chart/Chart.yaml | head -n1 | sed -E 's|^[[:space:]]*tjpa.jus.br/dev-source-repo:[[:space:]]*||' | tr -d '\"' | tr -d "\'")"
    - |
      if [ -z "$DEV_APP_REPO_URL" ]; then
        echo "Aviso: Anotação 'tjpa.jus.br/dev-source-repo' não encontrada no Chart.yaml."
      else
        echo "Detected dev source repo $DEV_APP_REPO_URL"
      fi
    - echo "CHART_VERSION=$CHART_VERSION" > variables.env
    - echo "DEV_APP_REPO_URL=$DEV_APP_REPO_URL" >> variables.env
  artifacts:
      reports:
        dotenv: variables.env

deploy_new_env:
  stage: deploy
  needs: ["get_chart_version"]
  trigger:
    project: "devops/cicd"
    branch: main
    strategy: depend
  variables:
    APP_NAME: $CI_PROJECT_NAME
    DEPLOY_MODE: "helm"
    ENV: $ENV_
    PROJ_CHART_VERSION: $CHART_VERSION
    ENABLE_CA_SOURCE: $ENABLE_CA_SOURCE
    DEV_APP_REPO_URL: $DEV_APP_REPO_URL
    DEV_APP_REPO_REVISION: $DEV_APP_REPO_REVISION
    DEV_VALUES_PATH: $DEV_VALUES_PATH

