{{- $app := index .Values "chart-model-single" | default dict -}}
{{- if and $app.files $app.files.cm -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-single.fullname" . }}-files
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
data:
{{- range $filename, $config := $app.files.cm }}
  {{ $filename }}: |
    {{- $config.content | nindent 4 }}
{{- end }}
{{- end }}
