{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp.files $comp.files.cm -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-single.fullname" . }}-files-cm
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
data:
{{- range $filename, $config := $comp.files.cm }}
  {{ $filename }}: |
    {{- $config.content | nindent 4 }}
{{- end }}
{{- end }}

{{- end }}
