{{- if and .Values.global .Values.global.config.env (not (empty .Values.global.config.env)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-single.fullname" . }}-global-cm
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.global.config.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
