{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp $comp.config.env (not (empty $comp.config.env)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-single.fullname" . }}-cm
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
data:
  {{- range $key, $val := $comp.config.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}

{{- end }}
