{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if ne $comp.enabled false }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart-model-single.fullname" . }}
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
  {{- $annotations := include "chart-model-single.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ $comp.schedule | quote }}
  concurrencyPolicy: {{ default "Allow" $comp.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ default 3 $comp.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 1 $comp.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "chart-model-single.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "chart-model-single.name" . }}
    spec:
      template:
        metadata:
          annotations:
            {{- if and .Values.global .Values.global.cm (not (empty .Values.global.cm)) }}
            checksum/global-config: '{{ include (print $.Template.BasePath "/cm-global.yaml") . | sha256sum }}'
            {{- end }}
            {{- if and $comp.files $comp.files.cm (not (empty $comp.files.cm)) }}
            checksum/cm-files: '{{ include (print $.Template.BasePath "/cm-files-cm.yaml") . | sha256sum }}'
            {{- end }}
            {{- if and $comp.files $comp.files.secret (not (empty $comp.files.secret)) }}
            checksum/secret-files: '{{ include (print $.Template.BasePath "/secret-files.yaml") . | sha256sum }}'
            {{- end }}
            {{- if and $comp.secret (not (empty $comp.secret)) }}
            checksum/secret: '{{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}'
            {{- end }}
          labels:
            {{- include "chart-model-single.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: {{ include "chart-model-single.name" . }}
        spec:
          {{- with $comp.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if and $comp.vso $comp.vso.enabled }}
          serviceAccountName: {{ include "chart-model-single.fullname" . }}-sa
          {{- else if .Values.serviceAccount }}
          serviceAccountName: {{ include "chart-model-single.serviceAccountName" . }}
          {{- end }}
          containers:
            - name: {{ include "chart-model-single.name" . }}
              image: "{{ $comp.image.repository }}:{{ $comp.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ $comp.image.pullPolicy }}
              {{- if $comp.command }}
              command:
                {{- toYaml $comp.command | nindent 16 }}
              {{- end }}
              {{- if $comp.args }}
              args:
                {{- toYaml $comp.args | nindent 16 }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ include "chart-model-single.fullname" . }}-global-cm
                - secretRef:
                    name: {{ include "chart-model-single.fullname" . }}-global-secret
                {{- if and $comp.cm (not (empty $comp.cm)) }}
                - configMapRef:
                    name: {{ include "chart-model-single.fullname" . }}-cm
                {{- end }}
                {{- if and $comp.secret (not (empty $comp.secret)) }}
                - secretRef:
                    name: {{ include "chart-model-single.fullname" . }}-secret
                {{- end }}
                {{- if and $comp.vso $comp.vso.enabled }}
                - secretRef:
                    name: {{ include "chart-model-single.fullname" . }}-vso-secret
                {{- end }}
              {{- if $comp.resources }}
              resources:
                {{- toYaml $comp.resources | nindent 16 }}
              {{- end }}
              volumeMounts:
                                {{- if and $comp.truststore $comp.truststore.enabled }}
                - name: truststore
                  mountPath: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
                  subPath: tls-ca-bundle.pem
                  readOnly: true
                {{- end }}
                {{- if and $comp.persistence $comp.persistence.enabled }}
                - name: {{ include "chart-model-single.name" . }}-data
                  mountPath: {{ $comp.persistence.mountPath | default "/data" }}
                  {{- if $comp.persistence.subPath }}
                  subPath: {{ $comp.persistence.subPath }}
                  {{- end }}
                {{- end }}
                {{- if and $comp.files $comp.files.cm }}
                {{- range $key, $val := $comp.files.cm }}
                - name: files
                  mountPath: {{ $val.path }}
                  subPath: {{ $key | replace "." "-" }}
                  readOnly: true
                {{- end }}
                {{- end }}
                {{- if and $comp.files $comp.files.secret }}
                {{- range $key, $val := $comp.files.secret }}
                - name: files-secret
                  mountPath: {{ $val.path }}
                  subPath: {{ $key | replace "." "-" }}
                  readOnly: true
                {{- end }}
                {{- end }}
                {{- if and $comp.vso $comp.vso.enabled $comp.vso.secretFiles }}
                {{- range $key, $val := $comp.vso.secretFiles }}
                - name: vso-files-secret
                  mountPath: {{ $val.path }}
                  subPath: {{ $key | replace "." "-" }}
                  readOnly: true
                {{- end }}
                {{- end }}
          volumes:
                        {{- if and $comp.truststore $comp.truststore.enabled }}
            - name: truststore
              secret:
                secretName: {{ include "chart-model-single.fullname" . }}-secret-truststore
            {{- end }}
            {{- if and $comp.persistence $comp.persistence.enabled }}
            - name: {{ include "chart-model-single.name" . }}-data
              {{- if $comp.persistence.ephemeral }}
              emptyDir: {}
              {{- else }}
              persistentVolumeClaim:
                claimName: {{ include "chart-model-single.fullname" . }}
              {{- end }}
            {{- end }}
            {{- if and $comp.files $comp.files.cm (not (empty $comp.files.cm)) }}
            - name: files
              configMap:
                name: {{ include "chart-model-single.fullname" . }}-files-cm
            {{- end }}
            {{- if and $comp.files $comp.files.secret (not (empty $comp.files.secret)) }}
            - name: files-secret
              secret:
                secretName: {{ include "chart-model-single.fullname" . }}-files-secret
            {{- end }}
            {{- if and $comp.vso $comp.vso.enabled $comp.vso.secretFiles }}
            - name: vso-files-secret
              secret:
                secretName: {{ include "chart-model-single.fullname" . }}-vso-secret
            {{- end }}
          restartPolicy: {{ default "OnFailure" $comp.restartPolicy }}
          {{- with $comp.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $comp.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $comp.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
