{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp.persistence (and $comp.persistence.enabled (not $comp.persistence.ephemeral)) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart-model-single.fullname" . }}
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ $comp.persistence.accessMode | default "ReadWriteOnce" }}
  {{- if $comp.persistence.storageClass }}
  {{- if (eq "-" $comp.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ $comp.persistence.storageClass }}"
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ $comp.persistence.storageRequest | default "1Gi" }}
{{- end }}

{{- end }}
