{{- $app := index .Values .Chart.Name | default dict -}}
{{- if and $app $app.route $app.route.default $app.route.default.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart-model-single.fullname" . }}
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
  {{- with $app.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $app.route.default.host }}
  host: {{ $app.route.default.host | quote }}
  {{- end }}
  {{- if $app.route.path }}
  path: {{ $app.route.path | quote }}
  {{- end }}
  {{- if $app.route.tls }}
  tls:
    {{- toYaml $app.route.tls | nindent 4 }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "chart-model-single.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{- end }}
