{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp $comp.route $comp.route.additional -}}
{{- range $routeName, $routeConfig := $comp.route.additional }}
{{- if ne $routeConfig.enabled false -}}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart-model-single.fullname" $ }}-{{ $routeName }}
  labels:
    {{- include "chart-model-single.labels" $ | nindent 4 }}
  {{- $annotations := merge ($routeConfig.annotations | default dict) ($comp.route.annotations | default dict) }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if $routeConfig.host }}
  host: {{ $routeConfig.host | quote }}
  {{- end }}
  {{- if $routeConfig.path }}
  path: {{ $routeConfig.path | quote }}
  {{- else if $comp.route.path }}
  path: {{ $comp.route.path | quote }}
  {{- end }}
  {{- if $routeConfig.tls }}
  tls:
    {{- toYaml $routeConfig.tls | nindent 4 }}
  {{- else if $comp.route.tls }}
  tls:
    {{- toYaml $comp.route.tls | nindent 4 }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "chart-model-single.fullname" $ }}
    weight: 100
  port:
    targetPort: {{ if and $comp.service $comp.service.ports }}{{ if hasKey $comp.service.ports "http" }}http{{ else }}{{ keys $comp.service.ports | first | default "http" }}{{ end }}{{ else }}http{{ end }}
  wildcardPolicy: None
{{- end }}
{{- end }}
{{- end }}
{{- end }}
