{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if ne (default true $comp.enabled) false }}
{{- if ne $comp.workloadType "CronJob" }}
{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if and $comp $comp.route $comp.route.default $comp.route.default.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart-model-single.fullname" . }}
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
  {{- with $comp.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $comp.route.default.host }}
  host: {{ $comp.route.default.host | quote }}
  {{- end }}
  {{- if $comp.route.path }}
  path: {{ $comp.route.path | quote }}
  {{- end }}
  {{- if $comp.route.tls }}
  tls:
    {{- toYaml $comp.route.tls | nindent 4 }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "chart-model-single.fullname" . }}
    weight: 100
  port:
    targetPort: {{ if and $comp.service $comp.service.ports }}{{ if hasKey $comp.service.ports "http" }}http{{ else }}{{ keys $comp.service.ports | first | default "http" }}{{ end }}{{ else }}http{{ end }}
  wildcardPolicy: None
{{- end }}
{{- end }}

{{- end }}
