{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp.truststore $comp.truststore.enabled $comp.truststore.certificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-single.fullname" . }}-secret-truststore
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "chart-model-single.name" . }}
type: Opaque
stringData:
  certificate.pem: |
    {{- $comp.truststore.certificate | nindent 4 }}
{{- end }}

{{- end }}
