{{- $app := index .Values "chart-model-single" | default dict -}}
{{- if and $app.files $app.files.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-single.fullname" . }}-files-secret
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $filename, $config := $app.files.secret }}
  {{ $filename }}: {{ $config.content | b64enc }}
{{- end }}
{{- end }}
