{{- if and .Values.global .Values.global.secrets.env (not (empty .Values.global.secrets.env)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-single.fullname" . }}-global-secret
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.global.secrets.env }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
