{{- range $name, $sidecar := .Values.component.extraContainers }}
{{- if and $sidecar $sidecar.secrets.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" $ }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-secret
  labels:
    {{- include "<CHART_NAME>.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml $sidecar.secrets.env | nindent 2 }}
---
{{- end }}
{{- end }}
{{- range $name, $sidecar := .Values.component.extraContainers }}
{{- if and $sidecar $sidecar.secrets $sidecar.secrets.files }}
{{- range $filename, $config := $sidecar.secrets.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" $ }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-{{ $filename | replace "." "-" | lower | trimAll "-" }}-secret
  labels:
    {{- include "<CHART_NAME>.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{ $filename }}: |-
    {{- $config.content | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
