{{- $app := index .Values .Chart.Name | default dict -}}
{{- if and $app $app.secret (not (empty $app.secret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-single.fullname" . }}-secret
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := $app.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
