{{- $app := index .Values .Chart.Name | default dict -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-model-single.fullname" . }}
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
spec:
  type: {{ $app.service.type }}
  ports:
    {{- $app.service.ports | toYaml | nindent 4 }}
  selector:
    {{- include "chart-model-single.selectorLabels" . | nindent 4 }}
