{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if ne $comp.enabled false }}
{{- if ne $comp.workloadType "CronJob" }}
{{- $comp := index .Values .Chart.Name | default dict -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-model-single.fullname" . }}
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
spec:
  type: {{ $comp.service.type }}
  ports:
    {{- range $key, $val := $comp.service.ports }}
  - name: {{ $key }}
    port: {{ $val.port }}
    targetPort: {{ $key }}
    {{- if $val.protocol }}
    protocol: {{ $val.protocol }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "chart-model-single.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "chart-model-single.name" . }}
{{- end }}

{{- end }}
