{{- $comp := index .Values .Chart.Name | default dict -}}
{{- if and $comp.vso $comp.vso.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "chart-model-single.fullname" . }}-vso-secret-obj
  labels:
    {{- include "chart-model-single.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ include "chart-model-single.fullname" . }}-vault-auth
  type: kv-v2
  mount: kv
  path: {{ .Values.vso.path | quote }}
  destination:
    name: {{ include "chart-model-single.fullname" . }}-vso-secret
    create: true
{{- end }}
