{{- if and .Values.postgres .Values.postgres.cm (not (empty .Values.postgres.cm)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-postgres-cm
  labels:
    {{- include "<CHART_NAME>.postgres.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.postgres.cm }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
