{{- if and .Values.postgres .Values.postgres.secret (not (empty .Values.postgres.secret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-postgres-secret
  labels:
    {{- include "<CHART_NAME>.postgres.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.postgres.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
