{{- if and .Values.postgres .Values.postgres.secrets.env (not (empty .Values.postgres.secrets.env)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-postgres-secret
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "postgres") | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.postgres.secrets.env }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
