apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "test-app.fullname" . }}-ingress
  {{- $annotations := include "test-app.myappIngress.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "test-app.myappIngress.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "test-app.fullname" . }}-myapp-service'
            port:
              number: 8443
        path: /testpath
        pathType: Prefix
