{{- if and .Values.redis .Values.redis.config.env (not (empty .Values.redis.config.env)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis-cm
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "redis") | nindent 4 }}
data:
  {{- range $key, $val := .Values.redis.config.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
