{{ if and .Values.redis .Values.redis.config .Values.redis.config.env (not (empty .Values.redis.config.env)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis-cm
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "redis") | nindent 4 }}
    {{- with .Values.redis.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range $key, $val := .Values.redis.config.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}

{{ if .Values.redis.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "redis") | nindent 4 }}
    {{- with .Values.redis.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $annotations := include "<CHART_NAME>.component.annotations" (dict "context" . "component" "redis") }}
  {{- if or $annotations .Values.redis.annotations }}
  annotations:
    {{- if $annotations }}
    {{- $annotations | nindent 4 }}
    {{- end }}
    {{- with .Values.redis.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if hasKey .Values.redis "replicas" }}
  replicas: {{ .Values.redis.replicas }}
  {{- end }}
  {{- if .Values.redis.strategy }}
  strategy:
    {{- toYaml .Values.redis.strategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "<CHART_NAME>.component.selectorLabels" (dict "context" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if $annotations }}
        {{- $annotations | nindent 8 }}
        {{- end }}
        {{- with .Values.redis.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "<CHART_NAME>.component.selectorLabels" (dict "context" . "component" "redis") | nindent 8 }}
        {{- with .Values.redis.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.redis.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy | default "IfNotPresent" }}
          ports:
            {{- range $key, $val := .Values.redis.service.ports }}
            - name: {{ $key }}
              containerPort: {{ $val.port }}
              {{- if $val.protocol }}
              protocol: {{ $val.protocol }}
              {{- end }}
            {{- end }}
          
          {{- if or (and .Values.redis.config .Values.redis.config.env (not (empty .Values.redis.config.env))) (and .Values.redis.secrets .Values.redis.secrets.env (not (empty .Values.redis.secrets.env))) (and .Values.global (not (empty .Values.global))) }}
          envFrom:
            {{- if and .Values.redis.config .Values.redis.config.env (not (empty .Values.redis.config.env)) }}
            - configMapRef:
                name: {{ include "<CHART_NAME>.fullname" . }}-redis-cm
            {{- end }}
            {{- if and .Values.redis.secrets .Values.redis.secrets.env (not (empty .Values.redis.secrets.env)) }}
            - secretRef:
                name: {{ include "<CHART_NAME>.fullname" . }}-redis-secret
            {{- end }}
            {{- if and .Values.global .Values.global.config .Values.global.config.env (not (empty .Values.global.config.env)) }}
            - configMapRef:
                name: {{ include "<CHART_NAME>.fullname" . }}-global-cm
            {{- end }}
            {{- if and .Values.global .Values.global.secrets .Values.global.secrets.env (not (empty .Values.global.secrets.env)) }}
            - secretRef:
                name: {{ include "<CHART_NAME>.fullname" . }}-global-secret
            {{- end }}
          {{- end }}

          {{- if and .Values.redis.probes .Values.redis.probes.startup (not (empty .Values.redis.probes.startup)) }}
          startupProbe:
            {{- toYaml .Values.redis.probes.startup | nindent 12 }}
          {{- end }}
          {{- if and .Values.redis.probes .Values.redis.probes.liveness (not (empty .Values.redis.probes.liveness)) }}
          livenessProbe:
            {{- toYaml .Values.redis.probes.liveness | nindent 12 }}
          {{- end }}
          {{- if and .Values.redis.probes .Values.redis.probes.readiness (not (empty .Values.redis.probes.readiness)) }}
          readinessProbe:
            {{- toYaml .Values.redis.probes.readiness | nindent 12 }}
          {{- end }}

          {{- with .Values.redis.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.redis.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- if and .Values.redis.resources .Values.redis.resources.limits }}
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          {{- end }}

          {{- if or (and .Values.redis.persistence .Values.redis.persistence.enabled) (and .Values.redis.config .Values.redis.config.files) (and .Values.redis.secrets .Values.redis.secrets.files) (and .Values.redis.vso .Values.redis.vso.enabled .Values.redis.vso.files) }}
          volumeMounts:
          {{- if and .Values.redis.persistence .Values.redis.persistence.enabled }}
            - name: data
              mountPath: {{ .Values.redis.persistence.mountPath | default "/data" }}
          {{- end }}
          {{- if and .Values.redis.config .Values.redis.config.files }}
          {{- range $filename, $config := .Values.redis.config.files }}
            - name: config-files
              mountPath: {{ $config.mountPath | default (printf "/etc/config/%s" $filename) }}
              subPath: {{ $filename }}
          {{- end }}
          {{- end }}
          {{- if and .Values.redis.secrets .Values.redis.secrets.files }}
          {{- range $filename, $config := .Values.redis.secrets.files }}
            - name: secret-files
              mountPath: {{ $config.mountPath | default (printf "/etc/secret/%s" $filename) }}
              subPath: {{ $filename }}
          {{- end }}
          {{- end }}
          {{- if and .Values.redis.vso .Values.redis.vso.enabled .Values.redis.vso.files }}
          {{- range $filename, $config := .Values.redis.vso.files }}
            - name: vso-files
              mountPath: {{ $config.mountPath | default (printf "/etc/vso/%s" $filename) }}
              subPath: {{ $filename }}
          {{- end }}
          {{- end }}
          {{- end }}
      
      {{- if .Values.redis.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.redis.terminationGracePeriodSeconds }}
      {{- end }}

      {{- with .Values.redis.scheduling.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.scheduling.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.redis.scheduling.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.redis.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.redis.topologySpreadConstraints | nindent 8 }}
      {{- end }}

      {{- if and .Values.redis.persistence .Values.redis.persistence.enabled }}
      volumes:
        - name: data
          {{- if .Values.redis.persistence.ephemeral }}
          emptyDir: {}
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "<CHART_NAME>.fullname" $ }}-redis
          {{- end }}
      {{- if and .Values.redis.config .Values.redis.config.files }}
        - name: config-files
          configMap:
            name: {{ include "<CHART_NAME>.fullname" . }}-redis-files-cm
      {{- end }}
      {{- if and .Values.redis.secrets .Values.redis.secrets.files }}
        - name: secret-files
          secret:
            secretName: {{ include "<CHART_NAME>.fullname" . }}-redis-files-secret
      {{- end }}
      {{- if and .Values.redis.vso .Values.redis.vso.enabled }}
        - name: vso-files
          secret:
            secretName: {{ include "<CHART_NAME>.fullname" . }}-redis-vso-secret
      {{- end }}
      {{- end }}
{{- end -}}

{{ if and .Values.redis.enabled (and .Values.redis.persistence.enabled (not .Values.redis.persistence.ephemeral)) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "redis") | nindent 4 }}
    {{- with .Values.redis.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.redis.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.storageRequest | quote }}
  {{- if .Values.redis.persistence.storageClass }}
  {{- if (eq "-" .Values.redis.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.redis.persistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end -}}

{{ if and .Values.redis .Values.redis.secrets .Values.redis.secrets.env (not (empty .Values.redis.secrets.env)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis-secret
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "redis") | nindent 4 }}
    {{- with .Values.redis.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  {{- range $key, $val := .Values.redis.secrets.env }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}

{{ if .Values.redis.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "redis") | nindent 4 }}
    {{- with .Values.redis.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.redis.service.type | default "ClusterIP" }}
  ports:
    {{- range $key, $val := .Values.redis.service.ports }}
  - name: {{ $key }}
    port: {{ $val.port }}
    targetPort: {{ $key }}
    {{- if $val.protocol }}
    protocol: {{ $val.protocol }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "<CHART_NAME>.component.selectorLabels" (dict "context" . "component" "redis") | nindent 4 }}
{{- end -}}

{{- if and .Values.redis .Values.redis.config .Values.redis.config.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis-files-cm
  labels:
    {{- include "<CHART_NAME>.labels" . | nindent 4 }}
data:
{{- range $filename, $config := .Values.redis.config.files }}
  {{ $filename }}: |
    {{- $config.content | nindent 4 }}
{{- end }}
{{- end }}

{{- if and .Values.redis .Values.redis.secrets .Values.redis.secrets.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis-files-secret
  labels:
    {{- include "<CHART_NAME>.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $filename, $config := .Values.redis.secrets.files }}
  {{ $filename }}: {{ if $config.b64enc }}{{ $config.content | quote }}{{ else }}{{ $config.content | b64enc | quote }}{{ end }}
{{- end }}
{{- end }}

{{- if and .Values.redis .Values.redis.vso .Values.redis.vso.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis-vso
  labels:
    {{- include "<CHART_NAME>.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: kv
  path: {{ .Values.redis.vso.path }}
  destination:
    name: {{ include "<CHART_NAME>.fullname" . }}-redis-vso-secret
    create: true
  refreshAfter: 60s
  vaultAuthRef: {{ .Values.redis.vso.role | default (printf "%s-%s-role" (include "<CHART_NAME>.fullname" .) "redis") }}
{{- end }}
