{{- if and .Values.redis .Values.redis.secrets.env (not (empty .Values.redis.secrets.env)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis-secret
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "redis") | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.redis.secrets.env }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
