{{- if and .Values.redis .Values.redis.secret (not (empty .Values.redis.secret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-redis-secret
  labels:
    {{- include "<CHART_NAME>.redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.redis.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
