{{- $comp := index .Values "api" | default dict -}}
{{- if ne (default true $comp.enabled) false }}
{{- if and $comp.files $comp.files.cm -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-api-files
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
data:
{{- range $filename, $config := $comp.files.cm }}
  {{ $filename }}: |
    {{- $config.content | nindent 4 }}
{{- end }}
{{- end }}

{{- end }}
