{{- if and .Values.backend .Values.backend.cm (not (empty .Values.backend.cm)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-backend-cm
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
data:
  {{- range $key, $val := .Values.backend.cm }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
