{{- $comp := index .Values "backend" | default dict -}}
{{- if and $comp.files $comp.files.cm -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-backend-files
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
data:
{{- range $filename, $config := $comp.files.cm }}
  {{ $filename }}: |
    {{- $config.content | nindent 4 }}
{{- end }}
{{- end }}
