{{- range $compName, $comp := .Values.components }}
{{- range $name, $sidecar := $comp.extraContainers }}
{{- if and $sidecar $sidecar.cm }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" $ }}-{{ $compName }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-cm
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
data:
  {{- toYaml $sidecar.cm | nindent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- range $compName, $comp := .Values.components }}
{{- range $name, $sidecar := $comp.extraContainers }}
{{- if and $sidecar $sidecar.files $sidecar.files.cm }}
{{- range $filename, $config := $sidecar.files.cm }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" $ }}-{{ $compName }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-{{ $filename | replace "." "-" | lower | trimAll "-" }}
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
data:
  {{ $filename }}: |-
    {{- $config.content | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
