{{- $comp := index .Values "frontend" | default dict -}}
{{- if $comp.files -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-frontend-files
  labels:
    {{- include "chart-model-multi.frontend.labels" . | nindent 4 }}
data:
{{- range $filename, $config := $comp.files }}
  {{ $filename }}: |
    {{- $config.content | nindent 4 }}
{{- end }}
{{- end }}
