{{- $comp := index .Values "global" | default dict -}}
{{- if and $comp (not (empty $comp)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-global-cm
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
data:
  {{- range $key, $val := $comp.cm }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
