apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-global
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.global }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
