{{- $comp := index .Values "app" | default dict -}}
{{- if and $comp $comp.hpa $comp.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-app
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" . "component" "app") | nindent 4 }}
spec:
  {{- with $comp.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  maxReplicas: {{ $comp.hpa.maxReplicas }}
  metrics:
    {{- toYaml $comp.hpa.metrics | nindent 4 }}
  minReplicas: {{ $comp.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart-model-multi.fullname" . }}-app
{{- end }}
