{{- $comp := index .Values "app" | default dict -}}
{{- if and $comp $comp.route $comp.route.external.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-app-ext
  labels:
    {{- include "chart-model-multi.app.labels" . | nindent 4 }}
  {{- with $comp.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $comp.route.external.host }}
  host: {{ $comp.route.external.host | quote }}
  {{- end }}
  {{- if $comp.route.path }}
  path: {{ $comp.route.path | quote }}
  {{- end }}
  {{- if $comp.route.tls }}
  tls:
    {{- toYaml $comp.route.tls | nindent 4 }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "chart-model-multi.fullname" . }}-app
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{- end }}
