{{- if and .Values.frontend .Values.frontend.route .Values.frontend.route.internal.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-frontend-int
  labels:
    {{- include "chart-model-multi.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.frontend.route.internal.host }}
  host: {{ .Values.frontend.route.internal.host | quote }}
  {{- end }}
  {{- if .Values.frontend.route.path }}
  path: {{ .Values.frontend.route.path | quote }}
  {{- end }}
  {{- if .Values.frontend.route.tls }}
  tls:
    {{- toYaml .Values.frontend.route.tls | nindent 4 }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "chart-model-multi.fullname" . }}-frontend
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{- end }}
