{{- $comp := index .Values "app" | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp.autoscaling $comp.autoscaling.enabled (eq $comp.autoscaling.engine "keda") -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-app
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" . "component" "app") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart-model-multi.fullname" . }}-app
  minReplicaCount: {{ $comp.autoscaling.keda.minReplicas | default 1 }}
  maxReplicaCount: {{ $comp.autoscaling.keda.maxReplicas | default 2 }}
  {{- with $comp.autoscaling.keda.pollingInterval }}
  pollingInterval: {{ . }}
  {{- end }}
  {{- with $comp.autoscaling.keda.cooldownPeriod }}
  cooldownPeriod: {{ . }}
  {{- end }}
  triggers:
    {{- range $trigger := $comp.autoscaling.keda.triggers }}
    - type: {{ $trigger.type }}
      metadata:
        {{- toYaml $trigger.metadata | nindent 8 }}
      authenticationRef:
        name: {{ include "chart-model-multi.fullname" $ }}-app-trigger-auth
    {{- end }}
{{- end }}
{{- end }}
