{{- if and .Values.api .Values.api.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-api-secrets
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
  {{- range $key, $val := .Values.api.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
