{{- if and .Values.global .Values.global.secret (not (empty .Values.global.secret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-global
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.global.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}
