{{- $compName := "frontend" -}}
{{- $comp := index .Values $compName | default dict -}}
{{- if and $comp.truststore $comp.truststore.enabled $comp.truststore.certificate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-{{ $compName }}-secret-truststore
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
type: Opaque
stringData:
  certificate.pem: |
    {{- $comp.truststore.certificate | nindent 4 }}
{{- end }}
