{{- $comp := index .Values "app" | default dict -}}
{{- if ne (default true $comp.enabled) false }}
{{- if and $comp.files $comp.files.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-app-files-secret
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $filename, $config := $comp.files.secret }}
{{- if $config.b64enc }}
  {{ $filename }}: {{ $config.content | quote }}
{{- else }}
  {{ $filename }}: {{ $config.content | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
