{{- if and .Values.frontend .Values.frontend.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-frontend-secret
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
type: Opaque
data:
  {{- range $key, $val := .Values.frontend.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
