{{- if and .Values.backend .Values.backend.secret (not (empty .Values.backend.secret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-backend-secret
  labels:
    {{- include "chart-model-multi.backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := .Values.backend.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
