{{- range $compName, $comp := .Values.components }}
{{- range $name, $sidecar := $comp.extraContainers }}
{{- if and $sidecar $sidecar.secrets.env }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" $ }}-{{ $compName }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-secret
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
type: Opaque
stringData:
  {{- toYaml $sidecar.secrets.env | nindent 2 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- range $compName, $comp := .Values.components }}
{{- range $name, $sidecar := $comp.extraContainers }}
{{- if and $sidecar $sidecar.secrets $sidecar.secrets.files }}
{{- range $filename, $config := $sidecar.secrets.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" $ }}-{{ $compName }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-{{ $filename | replace "." "-" | lower | trimAll "-" }}-secret
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
type: Opaque
stringData:
  {{ $filename }}: |-
    {{- $config.content | nindent 4 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
