{{- $comp := index .Values "api" | default dict -}}
{{- if and $comp.files $comp.files.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-api-secret-files
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $filename, $config := $comp.files.secret }}
  {{ $filename }}: |
    {{- $config.content | nindent 4 }}
{{- end }}
{{- end }}
