{{- $comp := index .Values "api" | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp $comp.secret (not (empty $comp.secret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-api-secret
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" . "component" "api") | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := $comp.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}

{{- end }}
