apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-backend
  labels:
    {{- include "chart-model-multi.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    {{- range $key, $val := .Values.backend.service.ports }}
  - name: {{ $key }}
    port: {{ $val.port }}
    targetPort: {{ $val.targetPort }}
    {{- if $val.protocol }}
    protocol: {{ $val.protocol }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "chart-model-multi.backend.selectorLabels" . | nindent 4 }}
