apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-backend
  labels:
    {{- include "chart-model-multi.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    {{- .Values.backend.service.ports | toYaml | nindent 4 }}
  selector:
    {{- include "chart-model-multi.backend.selectorLabels" . | nindent 4 }}
