{{- $comp := index .Values "api" | default dict -}}
{{- if ne $comp.enabled false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-api
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" . "component" "api") | nindent 4 }}
spec:
  type: {{ $comp.service.type }}
  ports:
    {{- range $key, $val := $comp.service.ports }}
  - name: {{ $key }}
    port: {{ $val.port }}
    targetPort: {{ $key }}
    {{- if $val.protocol }}
    protocol: {{ $val.protocol }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "chart-model-multi.component.selectorLabels" (dict "context" . "component" "api") | nindent 4 }}

{{- end }}
