apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-frontend
  labels:
    {{- include "chart-model-multi.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    {{- .Values.frontend.service.ports | toYaml | nindent 4 }}
  selector:
    {{- include "chart-model-multi.frontend.selectorLabels" . | nindent 4 }}
