{{- $comp := index .Values "frontend" | default dict -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-frontend
  labels:
    {{- include "chart-model-multi.frontend.labels" . | nindent 4 }}
spec:
  type: {{ $comp.service.type }}
  ports:
    {{- range $key, $val := $comp.service.ports }}
  - name: {{ $key }}
    port: {{ $val.port }}
    targetPort: {{ $key }}
    {{- if $val.protocol }}
    protocol: {{ $val.protocol }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "chart-model-multi.frontend.selectorLabels" . | nindent 4 }}
