{{- $comp := index .Values "app" | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp $comp.keda $comp.keda.enabled -}}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-app-trigger-auth
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" . "component" "app") | nindent 4 }}
spec:
  {{- with $comp.keda.triggerAuth }}
  {{- if .secretTargetRef }}
  secretTargetRef:
    {{- toYaml .secretTargetRef | nindent 4 }}
  {{- end }}
  {{- if .envTargetRef }}
  envTargetRef:
    {{- toYaml .envTargetRef | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
