{{- $comp := index .Values "api" | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp.autoscaling $comp.autoscaling.enabled (eq $comp.autoscaling.engine "keda") -}}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-api-trigger-auth
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" . "component" "api") | nindent 4 }}
spec:
  {{- with $comp.autoscaling.keda.triggerAuth }}
  {{- if .secretTargetRef }}
  secretTargetRef:
    {{- toYaml .secretTargetRef | nindent 4 }}
  {{- end }}
  {{- if .envTargetRef }}
  envTargetRef:
    {{- toYaml .envTargetRef | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
