{{- $comp := index .Values "api" | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp.vso $comp.vso.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-api-vault-auth
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: {{ $comp.vso.role | quote }}
    serviceAccount: {{ include "chart-model-multi.fullname" . }}-api-sa
{{- end }}

{{- end }}
