{{- $comp := index .Values "frontend" | default dict -}}
{{- if and $comp.vso $comp.vso.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-frontend-vso-secret-obj
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ include "chart-model-multi.fullname" . }}-frontend-vault-auth
  type: kv-v2
  mount: kv
  path: {{ $comp.vso.path | quote }}
  destination:
    name: {{ include "chart-model-multi.fullname" . }}-frontend-vso-secret
    create: true
{{- end }}
