{{- $comp := index .Values "app" | default dict -}}
{{- if ne (default true $comp.enabled) false }}
{{- if and $comp.vso $comp.vso.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-app-sa
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
{{- end }}

{{- end }}
