{{- $comp := index .Values "app" | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp.vso $comp.vso.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-app-vso-secret-obj
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ include "chart-model-multi.fullname" . }}-app-vault-auth
  type: kv-v2
  mount: kv
  path: {{ $comp.vso.path | quote }}
  destination:
    name: {{ include "chart-model-multi.fullname" . }}-app-vso-secret
    create: true
  rolloutRestartTargets:
    - kind: Deployment
      name: {{ include "chart-model-multi.fullname" . }}-app
{{- end }}

{{- end }}
