global:
  cm:
    TZ: America/Belem
  secret: {}
api:
  cm: {}
app-emissor:
  cm: {}
myapp:
  cm:
    dummyconfigmapkey: dummyconfigmapvalue
    my_config.properties: |
      health.healthProbeBindAddress=8081
      metrics.bindAddress=127.0.0.1:8080
    myval.yaml: |
      apiVersion: clickhouse.altinity.com/v1
      kind: ClickHouseInstallationTemplate
      metadata:
        name: default-oneperhost-pod-template
      spec:
        templates:
          podTemplates:
            - name: default-oneperhost-pod-template
              distribution: "OnePerHost"
    my.prop1: "1"
    my.prop2: val 1
    my.prop3: "true"
nginx:
  cm: {}
