{{- if and .Values.cronjob.enabled .Values.cronjob.config .Values.cronjob.config.files (not (empty .Values.cronjob.config.files)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-cronjob-files-cm
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "cronjob") | nindent 4 }}
data:
  {{- range $key, $val := .Values.cronjob.config.files }}
  {{ $key | replace "." "-" }}: |
    {{- $val.content | nindent 4 }}
  {{- end }}
{{- end }}
