{{- if and .Values.cronjob.enabled .Values.cronjob.truststore .Values.cronjob.truststore.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-cronjob-secret-truststore
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "cronjob") | nindent 4 }}
type: Opaque
data:
  tls-ca-bundle.pem: {{ required "A valid .Values.cronjob.truststore.content is required when truststore is enabled" .Values.cronjob.truststore.content | b64enc | quote }}
{{- end }}
