{{- if and .Values.cronjob.enabled .Values.cronjob.secret (not (empty .Values.cronjob.secret)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-cronjob-secret
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "cronjob") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.cronjob.secret }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
