{{- if and .Values.cronjob.enabled .Values.cronjob.secrets .Values.cronjob.secrets.files (not (empty .Values.cronjob.secrets.files)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-cronjob-files-secret
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "cronjob") | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.cronjob.secrets.files }}
  {{ $key | replace "." "-" }}: |
    {{- $val.content | nindent 4 }}
  {{- end }}
{{- end }}
