{{- if and .Values.cronjob.enabled .Values.cronjob.vso .Values.cronjob.vso.enabled -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "<CHART_NAME>.fullname" . }}-cronjob-vaultstaticsecret
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" . "component" "cronjob") | nindent 4 }}
spec:
  type: kv-v2
  mount: {{ .Values.cronjob.vso.secretMount | default "kv" }}
  path: {{ .Values.cronjob.vso.path }}
  destination:
    name: {{ include "<CHART_NAME>.fullname" . }}-cronjob-vso-secret
    create: true
  refreshAfter: {{ .Values.cronjob.vso.refreshAfter | default "30s" }}
  vaultAuthRef: {{ include "<CHART_NAME>.fullname" . }}-cronjob-vaultauth
{{- end }}
