{{- range $compName, $comp := .Values.deploys }}
{{- if ne $comp.enabled false }}
{{- if ne $comp.workloadType "CronJob" }}
{{- if and $comp.autoscaling $comp.autoscaling.enabled }}

{{- if eq $comp.autoscaling.engine "hpa" }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
spec:
  {{- with $comp.autoscaling.hpa.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  maxReplicas: {{ $comp.autoscaling.hpa.maxReplicas }}
  metrics:
    {{- toYaml $comp.autoscaling.hpa.metrics | nindent 4 }}
  minReplicas: {{ $comp.autoscaling.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}
{{- end }}

{{- if eq $comp.autoscaling.engine "keda" }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}
  minReplicaCount: {{ $comp.autoscaling.keda.minReplicas | default 1 }}
  maxReplicaCount: {{ $comp.autoscaling.keda.maxReplicas | default 2 }}
  {{- with $comp.autoscaling.keda.pollingInterval }}
  pollingInterval: {{ . }}
  {{- end }}
  {{- with $comp.autoscaling.keda.cooldownPeriod }}
  cooldownPeriod: {{ . }}
  {{- end }}
  triggers:
    {{- range $trigger := $comp.autoscaling.keda.triggers }}
    - type: {{ $trigger.type }}
      metadata:
        {{- toYaml $trigger.metadata | nindent 8 }}
      authenticationRef:
        name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-trigger-auth
    {{- end }}
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-trigger-auth
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
spec:
  {{- with $comp.autoscaling.keda.triggerAuth }}
  {{- if .secretTargetRef }}
  secretTargetRef:
    {{- toYaml .secretTargetRef | nindent 4 }}
  {{- end }}
  {{- if .envTargetRef }}
  envTargetRef:
    {{- toYaml .envTargetRef | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
---
{{- end }}
