{{- range $compName, $comp := .Values.deploys }}
{{- if ne $comp.enabled false }}
{{- if and $comp $comp.config.env (not (empty $comp.config.env)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" $ }}-{{ $compName }}-cm
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
data:
  {{- range $key, $val := $comp.config.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- if and $comp $comp.config $comp.config.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" $ }}-{{ $compName }}-files-cm
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
data:
{{- range $filename, $config := $comp.config.files }}
  {{ $filename }}: |
    {{- $config.content | nindent 4 }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
