{{ $comp := index .Values "global" | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp $comp.config $comp.config.env (not (empty $comp.config.env)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-global-cm
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
data:
  {{- range $key, $val := $comp.config.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}

{{- end }}
{{- range $compName, $comp := .Values.deploys }}
{{- range $name, $config := $comp.initContainers }}
{{- if ne ($config.enabled | default true) false }}
{{- if and $config.config $config.config.env }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-init-{{ $name | replace "." "-" | lower | trimAll "-" }}-cm
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
data:
  {{- range $key, $val := $config.config.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- range $compName, $comp := .Values.deploys }}
{{- range $name, $config := $comp.initContainers }}
{{- if ne ($config.enabled | default true) false }}
{{- if and $config.config $config.config.files }}
{{- range $filename, $fileconf := $config.config.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-init-{{ $name | replace "." "-" | lower | trimAll "-" }}-{{ $filename | replace "." "-" | lower | trimAll "-" }}
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
data:
  {{ $filename }}: |-
    {{- $fileconf.content | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- range $compName, $comp := .Values.deploys }}
{{- range $name, $sidecar := $comp.extraContainers }}
{{- if ne ($sidecar.enabled | default true) false }}
{{- if and $sidecar $sidecar.config $sidecar.config.env }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-cm
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
data:
  {{- range $key, $val := $sidecar.config.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- range $compName, $comp := .Values.deploys }}
{{- range $name, $sidecar := $comp.extraContainers }}
{{- if ne ($sidecar.enabled | default true) false }}
{{- if and $sidecar $sidecar.config $sidecar.config.files }}
{{- range $filename, $config := $sidecar.config.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-{{ $filename | replace "." "-" | lower | trimAll "-" }}
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
data:
  {{ $filename }}: |-
    {{- $config.content | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
