{{- range $compName, $comp := .Values.cronjobs }}
{{- if ne $comp.enabled false }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
  {{- $annotations := include "<CHART_NAME>.component.annotations" (dict "context" $ "component" $compName) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
spec:
  schedule: {{ $comp.schedule | quote }}
  {{- if hasKey $comp "suspend" }}
  suspend: {{ $comp.suspend }}
  {{- end }}
  concurrencyPolicy: {{ default "Allow" $comp.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ default 3 $comp.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ default 1 $comp.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "<CHART_NAME>.component.selectorLabels" (dict "context" . "component" $compName) | nindent 8 }}
    spec:
      template:
        metadata:
          annotations:
            {{- if $annotations }}
            {{- $annotations | nindent 12 }}
            {{- end }}
          labels:
            {{- include "<CHART_NAME>.component.selectorLabels" (dict "context" . "component" $compName) | nindent 12 }}
        spec:
          {{- with $comp.image.pullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if and $comp.vso $comp.vso.enabled }}
          serviceAccountName: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-sa
          {{- else if .Values.serviceAccount }}
          serviceAccountName: {{ include "chart-model-multi.serviceAccountName" . }}
          {{- end }}
          containers:
            - name: cronjob
              image: "{{ $comp.image.repository }}:{{ $comp.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ $comp.image.pullPolicy }}
              {{- if $comp.command }}
              command:
                {{- toYaml $comp.command | nindent 16 }}
              {{- end }}
              {{- if $comp.args }}
              args:
                {{- toYaml $comp.args | nindent 16 }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ include "chart-model-multi.fullname" $ }}-global-cm
                - secretRef:
                    name: {{ include "chart-model-multi.fullname" $ }}-global-secret
                {{- if and $comp.config $comp.config.env (not (empty $comp.config.env)) }}
                - configMapRef:
                    name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-cm
                {{- end }}
                {{- if and $comp.secrets $comp.secrets.env (not (empty $comp.secrets.env)) }}
                - secretRef:
                    name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-secret
                {{- end }}
                {{- if and $comp.vso $comp.vso.enabled }}
                - secretRef:
                    name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-vso-secret
                {{- end }}
              {{- if $comp.resources }}
              resources:
                {{- toYaml $comp.resources | nindent 16 }}
              {{- end }}
              volumeMounts:
                {{- if and $comp.persistence $comp.persistence.enabled }}
                - name: cronjob-data
                  mountPath: {{ $comp.persistence.mountPath | default "/data" }}
                  {{- if $comp.persistence.subPath }}
                  subPath: {{ $comp.persistence.subPath }}
                  {{- end }}
                {{- end }}
                {{- if and $comp.config $comp.config.files }}
                {{- range $key, $val := $comp.config.files }}
                - name: files
                  mountPath: {{ $val.path }}
                  subPath: {{ $key | replace "." "-" }}
                  readOnly: true
                {{- end }}
                {{- end }}
                {{- if and $comp.secrets $comp.secrets.files }}
                {{- range $key, $val := $comp.secrets.files }}
                - name: files-secret
                  mountPath: {{ $val.path }}
                  subPath: {{ $key | replace "." "-" }}
                  readOnly: true
                {{- end }}
                {{- end }}
                {{- if and $comp.vso $comp.vso.enabled $comp.vso.secretFiles }}
                {{- range $key, $val := $comp.vso.secretFiles }}
                - name: vso-files-secret
                  mountPath: {{ $val.path }}
                  subPath: {{ $key | replace "." "-" }}
                  readOnly: true
                {{- end }}
                {{- end }}
          {{- if $comp.extraContainers }}
          {{- toYaml $comp.extraContainers | nindent 12 }}
          {{- end }}
          volumes:
            {{- if and $comp.persistence $comp.persistence.enabled }}
            - name: cronjob-data
              {{- if $comp.persistence.ephemeral }}
              emptyDir: {}
              {{- else }}
              persistentVolumeClaim:
                claimName: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}
              {{- end }}
            {{- end }}
            {{- if and $comp.config $comp.config.files (not (empty $comp.config.files)) }}
            - name: files
              configMap:
                name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-files-cm
            {{- end }}
            {{- if and $comp.secrets $comp.secrets.files (not (empty $comp.secrets.files)) }}
            - name: files-secret
              secret:
                secretName: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-files-secret
            {{- end }}
          restartPolicy: {{ default "OnFailure" $comp.restartPolicy }}
          {{- with $comp.scheduling.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $comp.scheduling.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $comp.scheduling.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}

{{ if and $comp.enabled $comp.config $comp.config.files (not (empty $comp.config.files)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-files-cm
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
data:
  {{- range $key, $val := $comp.config.files }}
  {{ $key | replace "." "-" }}: |
    {{- $val.content | nindent 4 }}
  {{- end }}
{{- end }}

{{ if and $comp.enabled $comp.config $comp.config.env (not (empty $comp.config.env)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-cm
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
data:
  {{- range $key, $val := $comp.config.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}

{{ if and $comp.enabled $comp.secrets $comp.secrets.files (not (empty $comp.secrets.files)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-files-secret
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := $comp.secrets.files }}
  {{ $key | replace "." "-" }}: |
    {{- $val.content | nindent 4 }}
  {{- end }}
{{- end }}

{{ if and $comp.enabled $comp.secrets $comp.secrets.env (not (empty $comp.secrets.env)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-secret
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := $comp.secrets.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}

{{ if and $comp.enabled $comp.vso $comp.vso.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-sa
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
{{- end }}

{{ if and $comp.enabled $comp.vso $comp.vso.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-vaultauth
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
spec:
  method: kubernetes
  mount: {{ $comp.vso.mount | default "kubernetes" }}
  kubernetes:
    role: {{ $comp.vso.role }}
    serviceAccount: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-sa
    audiences:
      - vault
{{- end }}

{{ if and $comp.enabled $comp.vso $comp.vso.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-vaultstaticsecret
  labels:
    {{- include "<CHART_NAME>.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
spec:
  type: kv-v2
  mount: {{ $comp.vso.secretMount | default "kv" }}
  path: {{ $comp.vso.path }}
  destination:
    name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-vso-secret
    create: true
  refreshAfter: {{ $comp.vso.refreshAfter | default "30s" }}
  vaultAuthRef: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-vaultauth
{{- end }}

---
{{- end }}
