{{- if and .Values.global .Values.global.imageCredentials .Values.global.imageCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-registry" (include "chart-model-multi.fullname" .) }}
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  {{- $authsList := list }}

  {{- if not .Values.global.imageCredentials.registries }}
    {{- fail "global.imageCredentials.create is true, but no credentials found. Provide at least one registry under global.imageCredentials.registries." }}
  {{- end }}

  {{- range $key, $regConfig := .Values.global.imageCredentials.registries }}
    {{- $registry := $regConfig.registry | required (printf "registry is required for registries.%s" $key) }}
    {{- $username := $regConfig.username | required (printf "username is required for registries.%s" $key) }}
    {{- $password := $regConfig.password | required (printf "password is required for registries.%s" $key) }}
    {{- $email := $regConfig.email | default "" }}
    {{- $auth := printf "%s:%s" $username $password | b64enc }}
    {{- $authStr := printf "\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}" $registry $username $password $email $auth }}
    {{- $authsList = append $authsList $authStr }}
  {{- end }}

  {{- $authsJoined := join "," $authsList }}
  {{- $dockerConfig := printf "{\"auths\":{%s}}" $authsJoined }}
  .dockerconfigjson: {{ $dockerConfig | b64enc }}
{{- end }}
