{{- range $compName, $comp := .Values.deploys }}
{{- if ne $comp.enabled false }}
{{- if and $comp $comp.secrets.env (not (empty $comp.secrets.env)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-secret
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := $comp.secrets.env }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if and $comp $comp.secrets $comp.secrets.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-files-secret
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
type: Opaque
data:
{{- range $filename, $config := $comp.secrets.files }}
{{- if $config.b64enc }}
  {{ $filename }}: {{ $config.content | quote }}
{{- else }}
  {{ $filename }}: {{ $config.content | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}

{{- end }}
{{- end }}
