{{ $comp := index .Values "global" | default dict -}}
{{- if ne $comp.enabled false }}
{{- if and $comp $comp.secrets $comp.secrets.env (not (empty $comp.secrets.env)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.fullname" . }}-global-secret
  labels:
    {{- include "chart-model-multi.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $val := $comp.secrets.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end }}

{{- end }}
{{- range $compName, $comp := .Values.deploys }}
{{- range $name, $config := $comp.initContainers }}
{{- if ne ($config.enabled | default true) false }}
{{- if and $config.secrets $config.secrets.env }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-init-{{ $name | replace "." "-" | lower | trimAll "-" }}-secret
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
type: Opaque
stringData:
  {{- range $key, $val := $config.secrets.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- range $compName, $comp := .Values.deploys }}
{{- range $name, $config := $comp.initContainers }}
{{- if ne ($config.enabled | default true) false }}
{{- if and $config.secrets $config.secrets.files }}
{{- range $filename, $fileconf := $config.secrets.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-init-{{ $name | replace "." "-" | lower | trimAll "-" }}-{{ $filename | replace "." "-" | lower | trimAll "-" }}-secret
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
type: Opaque
{{- if $fileconf.b64enc }}
data:
{{- if $fileconf.content }}
  {{ $filename }}: {{ $fileconf.content | quote }}
{{- else }}
  {{ $filename }}: {{ $.Files.Get (printf "files/%s" $filename) | quote }}
{{- end }}
{{- else }}
stringData:
{{- if $fileconf.content }}
  {{ $filename }}: |-
    {{- $fileconf.content | nindent 4 }}
{{- else }}
  {{ $filename }}: |-
{{ $.Files.Get (printf "files/%s" $filename) | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- range $compName, $comp := .Values.deploys }}
{{- range $name, $sidecar := $comp.extraContainers }}
{{- if ne ($sidecar.enabled | default true) false }}
{{- if and $sidecar $sidecar.secrets $sidecar.secrets.env }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-secret
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
type: Opaque
stringData:
  {{- range $key, $val := $sidecar.secrets.env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- range $compName, $comp := .Values.deploys }}
{{- range $name, $sidecar := $comp.extraContainers }}
{{- if ne ($sidecar.enabled | default true) false }}
{{- if and $sidecar $sidecar.secrets $sidecar.secrets.files }}
{{- range $filename, $config := $sidecar.secrets.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}-{{ $name | replace "." "-" | lower | trimAll "-" }}-{{ $filename | replace "." "-" | lower | trimAll "-" }}-secret
  labels:
    {{- include "chart-model-multi.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $compName }}
type: Opaque
{{- if $config.b64enc }}
data:
{{- if $config.content }}
  {{ $filename }}: {{ $config.content | quote }}
{{- else }}
  {{ $filename }}: {{ $.Files.Get (printf "files/%s" $filename) | quote }}
{{- end }}
{{- else }}
stringData:
{{- if $config.content }}
  {{ $filename }}: |-
    {{- $config.content | nindent 4 }}
{{- else }}
  {{ $filename }}: |-
{{ $.Files.Get (printf "files/%s" $filename) | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
