{{- range $compName, $comp := .Values.deploys }}
{{- if ne $comp.enabled false }}
{{- if and $comp $comp.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart-model-multi.componentname" (dict "context" $ "component" $compName) }}
  labels:
    {{- include "chart-model-multi.component.labels" (dict "context" $ "component" $compName) | nindent 4 }}
spec:
  type: {{ $comp.service.type | default "ClusterIP" }}
  ports:
    {{- range $key, $val := $comp.service.ports }}
  - name: {{ $key }}
    port: {{ $val.port }}
    targetPort: {{ $key }}
    {{- if $val.protocol }}
    protocol: {{ $val.protocol }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "chart-model-multi.component.selectorLabels" (dict "context" $ "component" $compName) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
