{{- if and .Values.global .Values.global.config .Values.global.config.env (not (empty .Values.global.config.env)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-app.fullname" . }}-global-cm
  labels:
    {{- include "test-app.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.global.config.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end -}}
