apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "test-app.fullname" . }}-cronjob
  {{- $annotations := include "test-app.api.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "test-app.api.labels" . | nindent 4 }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - args: '[HELMIFY_WITH:api.args:14]'
{{- with (index .Values "api").command }}
            command:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            envFrom:
            {{- if and .Values.global .Values.global.cm (not (empty .Values.global.cm)) }}
            - configMapRef:
                name: {{ include "test-app.fullname" . }}-global-cm
            {{- end }}
            {{- if and .Values.global .Values.global.secret (not (empty .Values.global.secret)) }}
            - secretRef:
                name: {{ include "test-app.fullname" . }}-global-secret
            {{- end }}
            {{- if (index .Values "api").cm }}
            - configMapRef:
                name: {{ include "test-app.fullname" . }}-api-cm
            {{- end }}
            {{- if (index .Values "api").secret }}
            - secretRef:
                name: {{ include "test-app.fullname" . }}-api-secret
            {{- end }}
            image: '{{ (index .Values "api").image.repository }}:{{ (index .Values
              "api").image.tag | default .Chart.AppVersion }}'
            imagePullPolicy: '{{ (index .Values "api").imagePullPolicy }}'
{{- with (index .Values "api").livenessProbe }}
            livenessProbe:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            name: hello
{{- with (index .Values "api").readinessProbe }}
            readinessProbe:
              {{- toYaml . | nindent 14 }}
            {{- end }}
{{- with (index .Values "api").resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
{{- with (index .Values "api").startupProbe }}
            startupProbe:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          nodeSelector: '{{- toYaml (index .Values "api").nodeSelector | nindent 12
            }}'
          restartPolicy: OnFailure
          serviceAccountName: '{{ include "test-app.serviceAccountName" . }}'
          tolerations: '{{- toYaml (index .Values "api").tolerations | nindent 12
            }}'
          topologySpreadConstraints: '{{- toYaml (index .Values "api").topologySpreadConstraints
            | nindent 12 }}'
  schedule: '{{ (index .Values "api").schedule | quote }}'
