apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "test-app.fullname" . }}-job
  {{- $annotations := include "test-app.api.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "test-app.api.labels" . | nindent 4 }}
spec:
  backoffLimit: '{{ (index .Values "api").backoffLimit }}'
  template:
    spec:
      containers:
      - args: '[HELMIFY_WITH:api.args:10]'
{{- with (index .Values "api").command }}
        command:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
        {{- if and .Values.global .Values.global.cm (not (empty .Values.global.cm)) }}
        - configMapRef:
            name: {{ include "test-app.fullname" . }}-global-cm
        {{- end }}
        {{- if and .Values.global .Values.global.secret (not (empty .Values.global.secret)) }}
        - secretRef:
            name: {{ include "test-app.fullname" . }}-global-secret
        {{- end }}
        {{- if (index .Values "api").cm }}
        - configMapRef:
            name: {{ include "test-app.fullname" . }}-api-cm
        {{- end }}
        {{- if (index .Values "api").secret }}
        - secretRef:
            name: {{ include "test-app.fullname" . }}-api-secret
        {{- end }}
        image: '{{ (index .Values "api").image.repository }}:{{ (index .Values "api").image.tag
          | default .Chart.AppVersion }}'
{{- with (index .Values "api").livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        name: pi
{{- with (index .Values "api").readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- with (index .Values "api").resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- with (index .Values "api").startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      nodeSelector: '{{- toYaml (index .Values "api").nodeSelector | nindent 8 }}'
      restartPolicy: Never
      serviceAccountName: '{{ include "test-app.serviceAccountName" . }}'
      tolerations: '{{- toYaml (index .Values "api").tolerations | nindent 8 }}'
      topologySpreadConstraints: '{{- toYaml (index .Values "api").topologySpreadConstraints
        | nindent 8 }}'
