apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "test-app.fullname" . }}-poddisruptionbudget
  {{- $annotations := include "test-app.nginx.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "test-app.nginx.labels" . | nindent 4 }}
spec:
  minAvailable: {{ (index .Values "nginx").minAvailable }}
  maxUnavailable: {{ (index .Values "nginx").maxUnavailable }}
  selector:
    matchLabels:
      app: nginx
    {{- include "test-app.nginx.selectorLabels" . | nindent 6 }}
