{{- if and .Values.global .Values.global.secrets .Values.global.secrets.env (not (empty .Values.global.secrets.env)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-app.fullname" . }}-global-secret
  labels:
    {{- include "test-app.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $val := .Values.global.secrets.env }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
{{- end -}}
