{{ $comp := index .Values "myapp" | default dict }}
{{- if and $comp $comp.secrets $comp.secrets.env (not (empty $comp.secrets.env)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-app.fullname" . }}-myapp-secret
  {{- $annotations := include "test-app.myapp.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "test-app.myapp.labels" . | nindent 4 }}
type: opaque
data:
{{- range $key, $value := $comp.secrets.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
---
{{ $comp := index .Values "myapp" | default dict }}
{{- if and $comp $comp.secrets $comp.secrets.env (not (empty $comp.secrets.env)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-app.fullname" . }}-myapp-secret
  {{- $annotations := include "test-app.myapp.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "test-app.myapp.labels" . | nindent 4 }}
type: opaque
data:
{{- range $key, $value := $comp.secrets.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
