apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "test-app.fullname" . }}-web
  {{- $annotations := include "test-app.app-emissor.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "test-app.app-emissor.labels" . | nindent 4 }}
spec:
  replicas: '{{ (index .Values "app-emissor").replicas }}'
  selector:
    matchLabels:
      app: nginx
  serviceName: '{{ include "test-app.fullname" . }}-nginx'
  template:
    metadata:
      annotations:
        {{- if and (index .Values "app-emissor") (index .Values "app-emissor" "cm") }}
        checksum/cm-config: {{ include (print $.Template.BasePath "/cm-app-emissor.yaml") . | sha256sum }}
        {{- end }}
        {{- if and .Values.global .Values.global.cm (not (empty .Values.global.cm)) }}
        checksum/global-config: {{ include (print $.Template.BasePath "/cm-global.yaml") . | sha256sum }}
        {{- end }}
        {{- if and .Values.global .Values.global.secret (not (empty .Values.global.secret)) }}
        checksum/global-secret: {{ include (print $.Template.BasePath "/secret-global.yaml") . | sha256sum }}
        {{- end }}
        {{- if and (index .Values "app-emissor") (index .Values "app-emissor" "secret") }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret-app-emissor.yaml") . | sha256sum }}
        {{- end }}
      labels:
        app: nginx
    spec:
      containers:
      - envFrom:
        {{- if and .Values.global .Values.global.cm (not (empty .Values.global.cm)) }}
        - configMapRef:
            name: {{ include "test-app.fullname" . }}-global-cm
        {{- end }}
        {{- if and .Values.global .Values.global.secret (not (empty .Values.global.secret)) }}
        - secretRef:
            name: {{ include "test-app.fullname" . }}-global-secret
        {{- end }}
        {{- if (index .Values "app-emissor").cm }}
        - configMapRef:
            name: {{ include "test-app.fullname" . }}-app-emissor-cm
        {{- end }}
        {{- if (index .Values "app-emissor").secret }}
        - secretRef:
            name: {{ include "test-app.fullname" . }}-app-emissor-secret
        {{- end }}
        image: '{{ (index .Values "app-emissor").image.repository }}:{{ (index .Values
          "app-emissor").image.tag | default .Chart.AppVersion }}'
{{- with (index .Values "app-emissor").livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        name: nginx
        ports:
        - containerPort: 80
          name: web
{{- with (index .Values "app-emissor").readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- with (index .Values "app-emissor").resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- with (index .Values "app-emissor").startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www
      nodeSelector: '{{- toYaml (index .Values "app-emissor").nodeSelector | nindent
        8 }}'
      serviceAccountName: '{{ include "test-app.serviceAccountName" . }}'
      tolerations: '{{- toYaml (index .Values "app-emissor").tolerations | nindent 8
        }}'
      topologySpreadConstraints: '{{- toYaml (index .Values "app-emissor").topologySpreadConstraints
        | nindent 8 }}'
  updateStrategy: {}
  volumeClaimTemplates:
  - metadata:
      creationTimestamp: null
      name: www
    spec:
      accessModes:
      - ReadWriteOnce
      resources: '{{ (index .Values "app-emissor").volumeClaims.www | toYaml | nindent
        8 }}'
