apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app.fullname" . }}-nginx
  {{- $annotations := include "test-app.nginx.annotations" . }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "test-app.nginx.labels" . | nindent 4 }}{{ $comp := index .Values "nginx" | default dict }}
spec:
  type: {{ $comp.service.type }}
  selector:
    {{- include "test-app.nginx.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $key, $val := $comp.service.ports }}
  - name: {{ $key }}
    port: {{ $val.port }}
    targetPort: {{ $val.targetPort }}
    {{- if $val.protocol }}
    protocol: {{ $val.protocol }}
    {{- end }}
    {{- end }}
